import { EventEmitter } from '../../../stencil-public-runtime';
import 'nodelist-foreach-polyfill';
import { ITimeStepProps } from '../time-step/time-step';
import { IMouseState, TimeLineConstraint } from '../../base-timeline';
export declare class TimeSlider {
    timeLineConstraint: TimeLineConstraint;
    timeSteps: string[];
    loadedTimeStepMap: Map<number, string>;
    timeStepIndex: number;
    disableTimesteps: boolean;
    timeStepProperties: ITimeStepProps[];
    mouseState: IMouseState;
    constrainTimeline: boolean;
    el: HTMLElement;
    dateClicked: EventEmitter;
    constraintChanged: EventEmitter;
    private sliderHandleActive;
    private xOffset;
    private constraintLeftActive;
    private constraintRightActive;
    private handleElement;
    private constraintLeft;
    private constraintRight;
    private timeBarPositions;
    private timeStepSpacingService;
    private resetTimeLine;
    private resetTimeLineConstraints;
    private setInitialSelectedTimeStep;
    private timeStepUtils;
    constrainTimelineHandler(): void;
    watchHandler(): void;
    timeStepsOnChangeHandler(newVal: any, oldVal: any): void;
    watchMouseState(newVal: any, oldVal: any): void;
    componentWillLoad(): void;
    componentDidUpdate(): void;
    render(): any;
    componentDidLoad(): void;
    componentDidRender(): void;
    private refreshTimeBarsPositions;
    mouseUp(mouseXPos: number): void;
    mouseDown(): void;
    mouseMove(mouseXPos: number): void;
    private moveRightConstraint;
    private moveLeftConstraint;
    private findNearestTimeStepToPointer;
    private findNearestActiveTimeStepToPointer;
    private findNearestActiveTimeStep;
    private moveElement;
    private calculateSnapPosition;
    private timeStepIndexUpdate;
    private handleDateClick;
    private resetConstraints;
}
