import { b as bootstrapLazy } from './index-db3f3b83.js';
import { a as patchEsm } from './patch-3900edbd.js';
var defineCustomElements = function (win, options) {
    if (typeof window === 'undefined')
        return Promise.resolve();
    return patchEsm().then(function () {
        return bootstrapLazy([["time-slider_3", [[0, "time-slider", { "timeSteps": [16], "loadedTimeStepMap": [16], "timeStepIndex": [2, "time-step-index"], "disableTimesteps": [4, "disable-timesteps"], "timeStepProperties": [16], "mouseState": [16], "constrainTimeline": [4, "constrain-timeline"], "timeLineConstraint": [32] }], [0, "time-step", { "timeData": [16], "labelFormat": [1, "label-format"] }], [0, "timeline-warnings", { "firstTimeStep": [1, "first-time-step"], "lastTimeStep": [1, "last-time-step"], "warnings": [16] }]]], ["mobile-timeline_3", [[0, "time-line", { "timeSteps": [16], "loadedTimeStepMap": [16], "timeStepIndex": [2, "time-step-index"], "disableTimesteps": [4, "disable-timesteps"], "labelFormat": [1, "label-format"], "warnings": [16], "mouseState": [16], "constrainTimeline": [4, "constrain-timeline"], "timeLineConstraint": [32] }, [[0, "constraintChanged", "constraintChangedHandler"]]], [0, "mobile-timeline", { "timeSteps": [16], "loadedTimeStepMap": [16], "disableTimesteps": [4, "disable-timesteps"], "timeStepIndex": [8, "time-step-index"] }, [[0, "newIndexSelected", "newIndex"]]], [0, "play-buttons", { "disablePlayButton": [4, "disable-play-button"], "playing": [4] }]]], ["mo-timeline", [[4, "mo-timeline", { "dateLabelFormat": [1, "date-label-format"], "timeLineLabelFormat": [1, "time-line-label-format"], "mobileTimelineBreakPoint": [2, "mobile-timeline-break-point"], "timeStepIndex": [2, "time-step-index"], "warnings": [16], "timesteps": [8], "loadedTimesteps": [8, "loaded-timesteps"], "defaultTimestepState": [1, "default-timestep-state"], "disablePlayButton": [4, "disable-play-button"], "constrainTimeline": [4, "constrain-timeline"], "mouseState": [16], "timezone": [1], "currentContainerWidth": [32], "playing": [32], "timeLineConstraint": [32], "disableTimesteps": [32], "play": [64], "forward": [64], "backward": [64] }, [[0, "constraintChanged", "constraintChangedHandler"], [0, "dateClicked", "dateClickedHandler"], [0, "forwardClicked", "forwardClickedHandler"], [0, "backClicked", "backClickedHandler"], [0, "playPauseClicked", "playPauseClickedHandler"], [1, "mouseleave", "mouseLeaveHandler"], [1, "mouseover", "mouseOverHandler"], [1, "mousedown", "mouseDownHandler"], [1, "mouseup", "mouseUpHandler"], [1, "mousemove", "mouseMoveHandler"]]]]]], options);
    });
};
export { defineCustomElements };
