
// MDDA Maps API

// Docs: https://metoffice.sharepoint.com/sites/technologyservicehubservice/SitePages/Map%20Layers%20Template.aspx

// RADAR Capabilities

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311


// RADAR - 5 possible styles

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=radar_uk_and_ireland_500_m_rain_rate_composite
    &STYLES=bmp_fill_gy_yl_wh_001_128_mmh1
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=radar_uk_and_ireland_500_m_rain_rate_composite
    &STYLES=bmp_fill_gy_yl_wh_001_128_mmh1_no_mask
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=radar_uk_and_ireland_500_m_rain_rate_composite
    &STYLES=bmp_fill_bu_yl_wh_001_32_mmh1_no_mask
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=radar_uk_and_ireland_500_m_rain_rate_composite
    &STYLES=bmp_fill_bu_yl_rd_001_100_mmh1_no_mask
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/radar?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=radar_uk_and_ireland_500_m_rain_rate_composite
    &STYLES=bmp_fill_bu_gn_yl_001_100_mmh1_no_mask_accessible
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311
