
// MDDA Maps API

// Docs: https://metoffice.sharepoint.com/sites/technologyservicehubservice/SitePages/Map%20Layers%20Template.aspx

// UKV Short/Medium Capabilities

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

// PROD 
GET https://mdda.hub.metoffice.cloud/wms/ukv/processed?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311



// UKV Short/Medium Temperature Screen Level - 5 possible styles

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=iso_fill_wh_gn_bk_ms50_ps50_c_line_bk_10
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=iso_fill_wh_gn_bk_ms100_ps50_c_line_bk_10
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=iso_fill_bk_bu_rd_ms30_ps36_c
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=iso_fill_bu_gn_rd_ms40_ps40_c
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=num_bu_rd_c
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###


###

// DEV Test Temperature Layer

GET https://rob-091023.mdda.hub.metoffice.cloud/wms/commercial/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://rob-091023.mdda.hub.metoffice.cloud/wms/commercial/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &STYLES=iso_fill_bk_bu_rd_ms20_ps36_c_2_c
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/ukv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=temperature_at_screen_level
    &CRS=EPSG:3857
    &BBOX=-1558472.87110583,6106854.834885074,779236.435552915,8625823.200203594
    &WIDTH=1910
    &HEIGHT=2060
    &STYLES=iso_fill_bk_bu_rd_ms30_ps36_c
    //&REFERENCE_TIME=2023-11-10T14:00:00Z
    //&TIME=2023-11-12T08:00:00Z
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311
