
// MDDA Maps API

// Docs: https://metoffice.sharepoint.com/sites/technologyservicehubservice/SitePages/Map%20Layers%20Template.aspx

// GLOBAL Long Capabilities

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 1234


// GLOBAL Long Wind Speed and Direction (Surface adjusted) - 6 possible styles

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=brb_wh_gn_rd_0_58_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=str_wh_gn_rd_0_58_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=arr_wh_gn_rd_0_58_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=iso_fill_wh_gn_rd_0_58_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=brb_bk_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234

###

GET https://dev.mdda.hub.metoffice.cloud/wms/glm/long?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=wind_speed_and_direction_from_which_blowing_surface_adjusted
    &STYLES=str_bk_kt
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 1234
