
// MDDA Maps API

// Docs: https://metoffice.sharepoint.com/sites/technologyservicehubservice/SitePages/Map%20Layers%20Template.aspx

// GLOBAL Short Capabilities

###

GET https://mdda.hub.metoffice.cloud/wms/glm?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311


// GLOBAL Long Mean Sea Level Pressure - 5 possible styles

###

GET https://mdda.hub.metoffice.cloud/wms/glm?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=mean_sea_level_pressure
    &STYLES=iso_bk_2_hpa
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/glm?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=mean_sea_level_pressure
    &STYLES=iso_bk_large_label_2_hpa
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/glm?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=mean_sea_level_pressure
    &STYLES=iso_bk_4_hpa
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311

###

GET https://mdda.hub.metoffice.cloud/wms/glm?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=FALSE
    &LAYERS=mean_sea_level_pressure
    &STYLES=iso_bk_large_label_4_hpa
    &CRS=CRS:84
    &BBOX=-25,44,16,64
    &WIDTH=1800
    &HEIGHT=1200
x-api-key: 88647c448e04edb1ff218b72ebe4ec24c8ef0e7e389b33398b57ef3250732311
