name: Merge to DEVELOP branch

###############################################################################
#
# 

on:
    push:
        branches:
            - '**'

    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    TEST:
        name: Deploy to TEST
        runs-on: ubuntu-latest
        timeout-minutes: 20
        environment: Test
        env:
            STACK_NAME: ${{vars.STACK_NAME}}
        steps:
            - name: Message
              run: echo "Deploying to ${{env.STACK_NAME}}"

            - name: Test
              run: echo ${{env.STACK_NAME}}Warnings-Manager-Stack

            - name: Another
              run: echo "${{env.STACK_NAME}}Warnings-Manager-Stack"              
